### ISSUE TITLE
frei0r-plugins-1.6.0.tar.gz 404 not found

### ISSUE THREAD

**Issue by rzcat** [DeadSix27/python_cross_compile_script#15]
Fedora 25, succeeded on building ffmpeg using rdp's script
using your script, need run
`dnf install gettext-devel gperf`
first, then execute 
`./cross_compiler.py -pl ffmpeg_static_non_free_opencl`
stuck at
```
[12:25:02][INFO] Downloading frei0r-plugins-1.6.0.tar.gz (https://files.dyne.org/frei0r/frei0r-plugins-1.6.0.tar.gz)
Traceback (most recent call last):
  File "./cross_compiler.py", line 607, in download_file
	response = opener.open(request)
  File "/usr/lib64/python3.5/urllib/request.py", line 472, in open
	response = meth(req, response)
  File "/usr/lib64/python3.5/urllib/request.py", line 582, in http_response
	'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python3.5/urllib/request.py", line 510, in error
	return self._call_chain(*args)
  File "/usr/lib64/python3.5/urllib/request.py", line 444, in _call_chain
	result = func(*args)
  File "/usr/lib64/python3.5/urllib/request.py", line 590, in http_error_default
	raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```
should i be using frei0r-plugins-1.6.1.tar.gz instead?

**Comment by DeadSix27** [comment]
@rzcat Merged your PR! Thanks!
EDIT: Stuck, as in, real stuck or just stopped there, e.g program exited? It should not get stuck, just exit.

**Comment by rzcat** [comment]
@DeadSix27 exit, not a real stuck, sorry..
