### ISSUE TITLE
toolchain build failure

### ISSUE THREAD

**Issue by hydra3333** [DeadSix27/python_cross_compile_script#41]
Hello,

I downloaded and extracted the .py and ran it like this

`u@ubuntu:~/Desktop/DeadSiz27$ ./cross_compiler.py  --debug --build_all --force`

but it crashed ... advice welcomed.

```
checking for gcc version with buggy 64-bit support... no
checking for ftello... yes
checking for ftello64... yes
checking for fseeko... yes
checking for fseeko64... yes
checking for fopen64... yes
checking size of off_t... 8
checking file_ptr type... BFD_HOST_64_BIT
checking for stdlib.h... (cached) yes
checking for unistd.h... (cached) yes
checking for getpagesize... (cached) yes
checking for working mmap... yes
checking for madvise... yes
checking for mprotect... yes
configure: updating cache ./config.cache
configure: creating ./config.status
config.status: creating Makefile
config.status: creating doc/Makefile
config.status: creating bfd-in3.h
config.status: creating po/Makefile.in
config.status: creating config.h
config.status: executing depfiles commands
config.status: executing libtool commands
config.status: executing default-1 commands
config.status: executing bfd_stdint.h commands
config.status: executing default commands
make[1]: Leaving directory '/home/u/Desktop/DeadSiz27/workdir/toolchain/bld/binutils-2.30'
Makefile:850: recipe for target 'all' failed
make: *** [all] Error 2
[16:07:24][INFO] [TOOLCHAIN] Error [2] running process: 'make  -j2 V=1' in '/home/u/Desktop/DeadSiz27/workdir/toolchain/bld/binutils-2.30'
[16:07:24][INFO] [TOOLCHAIN] You can try deleting the product/dependency folder: '/home/u/Desktop/DeadSiz27/workdir/toolchain/bld/binutils-2.30' and re-run the script
u@ubuntu:~/Desktop/DeadSiz27$ 
```

[build-crash-01.txt](https://github.com/DeadSix27/python_cross_compile_script/files/1755742/build-crash-01.txt)

**Comment by DeadSix27** [comment]
@hydra3333 

In a fully clean folder, download the main .py
open it, replace the url of `_MINGW_SCRIPT_URL` with: `https://dsix.site/patches/build_mingw_toolchain.py`

And only run: ./cross_compiler.py -d zlib

On my end it builds just fine, so I can't reproduce it..
__
Also mind using https://0x0.st/ for logs in the future, (or any other file hoster), github one doesn't allow viewing in browser and requires downloading (which is rather time consuming).

**Comment by hydra3333** [comment]
Same result

```
checking file_ptr type... BFD_HOST_64_BIT
checking for stdlib.h... (cached) yes
checking for unistd.h... (cached) yes
checking for getpagesize... (cached) yes
checking for working mmap... yes
checking for madvise... yes
checking for mprotect... yes
configure: updating cache ./config.cache
configure: creating ./config.status
config.status: creating Makefile
config.status: creating doc/Makefile
config.status: creating bfd-in3.h
config.status: creating po/Makefile.in
config.status: creating config.h
config.status: executing depfiles commands
config.status: executing libtool commands
config.status: executing default-1 commands
config.status: executing bfd_stdint.h commands
config.status: executing default commands
make[1]: Leaving directory '/home/u/Desktop/pydebug/workdir/toolchain/bld/binutils-2.30'
Makefile:850: recipe for target 'all' failed
make: *** [all] Error 2
[19:29:38][INFO] [TOOLCHAIN] Error [2] running process: 'make  -j2 V=1' in '/home/u/Desktop/pydebug/workdir/toolchain/bld/binutils-2.30'
[19:29:38][INFO] [TOOLCHAIN] You can try deleting the product/dependency folder: '/home/u/Desktop/pydebug/workdir/toolchain/bld/binutils-2.30' and re-run the script
u@ubuntu:~/Desktop/pydebug$ 
```

Ubuntu 17.10.1 ?

**Comment by DeadSix27** [comment]
@hydra3333 
```
checking which gmp to use... system
checking gmp.h usability... no
checking gmp.h presence... no
checking for gmp.h... no
configure: error: gmp.h header not found
```

Can't find gmp for whatever reason, probably the symlink not working?
Are you sure the user you run it as can create symlinks, do symlinks work in general?
EDIT: Are you sure it extracts properly? Check src/gmp or so

I updated the mingw script and added a debug line:
`print("DEBUG: Symlinking from '%s' to '%s' (we are in: %s)" % (SOURCES[sl[0]]["sourceFolder"],sl[1],os.getcwd()))`

Use it: https://dsix.site/patches/build_mingw_toolchain.py

Build again and see if you spot the messages: DEBUG: Symlinking from... then see if the symlinks it tried to create are actually there.

**Comment by hydra3333** [comment]
OK I just edited the main .py to use https://dsix.site/patches/build_mingw_toolchain.py  and ran it again as ./cross_compiler.py -d zlib

It's a vanilla ubuntu 17.10.1

if it doesn't work I'll try it again under sudo ?

edit: result the same

```
configure: updating cache ./config.cache
configure: creating ./config.status
config.status: creating Makefile
config.status: creating doc/Makefile
config.status: creating bfd-in3.h
config.status: creating po/Makefile.in
config.status: creating config.h
config.status: executing depfiles commands
config.status: executing libtool commands
config.status: executing default-1 commands
config.status: executing bfd_stdint.h commands
config.status: executing default commands
make[1]: Leaving directory '/home/u/Desktop/pydebug/workdir/toolchain/bld/binutils-2.30'
Makefile:850: recipe for target 'all' failed
make: *** [all] Error 2
[20:28:18][INFO] [TOOLCHAIN] Error [2] running process: 'make  -j2 V=1' in '/home/u/Desktop/pydebug/workdir/toolchain/bld/binutils-2.30'
[20:28:18][INFO] [TOOLCHAIN] You can try deleting the product/dependency folder: '/home/u/Desktop/pydebug/workdir/toolchain/bld/binutils-2.30' and re-run the script
u@ubuntu:~/Desktop/pydebug$ 

```

**Comment by DeadSix27** [comment]
@hydra3333 Read my last post again.

**Comment by hydra3333** [comment]
re-downloading, re-running, and checkling now ...

**Comment by hydra3333** [comment]
These debug statements showed

```
DEBUG: Symlinking from '/home/u/Desktop/pydebug/s/toolchain/src/isl-0.18' to 'isl' (we are in: /home/u/Desktop/pydebug/s/toolchain/src/binutils-2.30)
DEBUG: Symlinking from '/home/u/Desktop/pydebug/s/toolchain/src/gmp-6.1.2' to 'gmp' (we are in: /home/u/Desktop/pydebug/s/toolchain/src/gcc-7.3.0)
DEBUG: Symlinking from '/home/u/Desktop/pydebug/s/toolchain/src/mpfr-4.0.1' to 'mpfr' (we are in: /home/u/Desktop/pydebug/s/toolchain/src/gcc-7.3.0)
DEBUG: Symlinking from '/home/u/Desktop/pydebug/s/toolchain/src/mpc-1.1.0' to 'mpc' (we are in: /home/u/Desktop/pydebug/s/toolchain/src/gcc-7.3.0)
DEBUG: Symlinking from '/home/u/Desktop/pydebug/s/toolchain/src/isl-0.18' to 'isl' (we are in: /home/u/Desktop/pydebug/s/toolchain/src/gcc-7.3.0)
```

A "ls" of these showed files in them
```
/home/u/Desktop/pydebug/s/toolchain/src/binutils-2.30/isl
/home/u/Desktop/pydebug/s/toolchain/src/gcc-7.3.0/gmp
/home/u/Desktop/pydebug/s/toolchain/src/gcc-7.3.0/mpfr
/home/u/Desktop/pydebug/s/toolchain/src/gcc-7.3.0/mpc
/home/u/Desktop/pydebug/s/toolchain/src/gcc-7.3.0/isl
```

so my guess is the symlinks worked.

All the folders under src had files in them.

**Comment by DeadSix27** [comment]
@hydra3333 if you ls inside them, are there files too? Try:

```
cd /home/u/Desktop/pydebug/s/toolchain/src/gcc-7.3.0/
readlink -f gmp
ls gmp/
```

**Comment by hydra3333** [comment]
OK.  Here you go.

Does it matter that I run it on the same VM ubuntu 17.10.1 as I'd been using to build things via rdp's script ?  Or doesit need a brand new fresh VM ?
```
u@ubuntu:~$ cd /home/u/Desktop/pydebug/s/toolchain/src/gcc-7.3.0/
u@ubuntu:~/Desktop/pydebug/s/toolchain/src/gcc-7.3.0$ 
u@ubuntu:~/Desktop/pydebug/s/toolchain/src/gcc-7.3.0$ 
u@ubuntu:~/Desktop/pydebug/s/toolchain/src/gcc-7.3.0$ readlink -f gmp
/home/u/Desktop/pydebug/s/toolchain/src/gmp-6.1.2
u@ubuntu:~/Desktop/pydebug/s/toolchain/src/gcc-7.3.0$ ls gmp/
acinclude.m4      COPYINGv3          invalid.c      NEWS
aclocal.m4        cxx                longlong.h     nextprime.c
assert.c          demos              ltmain.sh      primesieve.c
AUTHORS           doc                Makefile.am    printf
bootstrap.c       errno.c            Makefile.in    rand
ChangeLog         extract-dbl.c      memory.c       README
compat.c          gen-bases.c        mini-gmp       scanf
compile           gen-fac.c          missing        tal-debug.c
configfsf.guess   gen-fib.c          mp_bpl.c       tal-notreent.c
configfsf.sub     gen-jacobitab.c    mp_clz_tab.c   tal-reent.c
config.guess      gen-psqr.c         mp_dv_tab.c    test-driver
config.in         gen-trialdivtab.c  mpf            tests
config.sub        gmp-h.in           mp_get_fns.c   tune
configure         gmp-impl.h         mp_minv_tab.c  version.c
configure.ac      gmpxx.h            mpn            ylwrap
COPYING           INSTALL            mpq
COPYING.LESSERv3  INSTALL.autoconf   mp_set_fns.c
COPYINGv2         install-sh         mpz
u@ubuntu:~/Desktop/pydebug/s/toolchain/src/gcc-7.3.0$ 
```

**Comment by DeadSix27** [comment]
@hydra3333 as long the root is clean (e.g /Desktop/pydebug/s/ doesn't have rdps script in) and your paths are reset it should be fine.
E.g your path shouldn't contain rdps mingw binary path, check by: "echo $PATH" 


I'm installing a ubuntu 17.10 VM and running my script, we'll see if i encounter the same issue.

**Comment by hydra3333** [comment]
Should be OK.

```
u@ubuntu:~/Desktop/pydebug/s/toolchain/src/gcc-7.3.0$ echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
u@ubuntu:~/Desktop/pydebug/s/toolchain/src/gcc-7.3.0$ 
```

**Comment by hydra3333** [comment]
OK and thank you.  Sorry to put you to this trouble.

**Comment by DeadSix27** [comment]
Okay fixed it, no idea why it works just fine in ArchLinux, but bugs in Ubuntu, my suspicion goes towards ubuntu using GCC 7.2.0  and my script builds 7.3.0, where as Arch uses 7.3.0 and maybe gmp versions differ on both too.. but I didn't even know that matters... (still don't).

Either way, giving binutils a symlink to gmp as well makes it build fine on ubuntu 17.10 apparently.. 

Re-run the script with mingw-script set to: https://dsix.site/patches/build_mingw_toolchain.py

Make sure to delete the old build_mingw_toolchain.py..

Check its _VERSION, should be 4.0 now, rather than 3.0.

**Comment by hydra3333** [comment]
`Running Python3 MinGW Build Script v4.1`

**Comment by DeadSix27** [comment]
@hydra3333 should work with that version now, try it.

**Comment by DeadSix27** [comment]
@hydra3333 should work with that version now, try it.

**Comment by hydra3333** [comment]
It is, thank you.  Sourceforge is very flakey tonight though :( :(

```
############ PKG_CONFIG_LIBDIR : 
############ CFLAGS : -march=sandybridge -O3
[22:57:09][INFO] Building dependencies of 'libpng'
[22:57:09][INFO] Building DEPENDENCY 'libpng'
Changing dir from /home/u/Desktop/pydebug/workdir to x86_64
[22:57:09][INFO] Downloading libpng-1.6.34.tar.xz (https://sourceforge.net/projects/libpng/files/libpng16/1.6.34/libpng-1.6.34.tar.xz)
Traceback (most recent call last):
  File "./cross_compiler.py", line 4213, in <module>
    main.commandLineEntrace()
  File "./cross_compiler.py", line 390, in commandLineEntrace
    self.defaultEntrace()
  File "./cross_compiler.py", line 412, in defaultEntrace
    self.build_thing(p,self.PRODUCTS[p],"PRODUCT")
  File "./cross_compiler.py", line 1221, in build_thing
    self.build_thing(libraryName,self.DEPENDS[libraryName],"DEPENDENCY")
  File "./cross_compiler.py", line 1221, in build_thing
    self.build_thing(libraryName,self.DEPENDS[libraryName],"DEPENDENCY")
  File "./cross_compiler.py", line 1221, in build_thing
    self.build_thing(libraryName,self.DEPENDS[libraryName],"DEPENDENCY")
  File "./cross_compiler.py", line 1266, in build_thing
    workDir = self.download_unpack_file(data["url"],None,workDir)
  File "./cross_compiler.py", line 1134, in download_unpack_file
    self.download_file(url,fileName)
  File "./cross_compiler.py", line 581, in download_file
    req.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 937, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://sourceforge.net/projects/libpng/files/libpng16/1.6.34/libpng-1.6.34.tar.xz

```

**Comment by DeadSix27** [comment]
Use: https://fossies.org/linux/misc/libpng-1.6.34.tar.xz
Also, you should prob use this version of my script: https://github.com/DeadSix27/python_cross_compile_script/tree/freetype_harfbuzz_testing

It has mirror and hash support, im still fixing other stuff in it ,  but its already working for the most part (ffmpeg, etc compiles all fine)

**Comment by hydra3333** [comment]
ooh, nice.  thank you.

**Comment by DeadSix27** [comment]
Sourceforge was actually the sole reason why I added mirror support.. 'cuz their shitty slow servers with 50% downtime are getting on my nerves
